version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_app
    restart: unless-stopped
    tty: true
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    ports:
      - "8000:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - restaurant_network
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: restaurant_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: restaurant_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: restaurant_user
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - restaurant_network

  redis:
    image: redis:7-alpine
    container_name: restaurant_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - restaurant_network

networks:
  restaurant_network:
    driver: bridge

volumes:
  db_data:
    driver: local
