version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: restaurant-app
    container_name: restaurant-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - restaurant-network

  db:
    image: mysql:8
    container_name: restaurant-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: restaurant
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - restaurant-network

  nginx:
    image: nginx:alpine
    container_name: restaurant-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - restaurant-network

volumes:
  dbdata:

networks:
  restaurant-network:
    driver: bridge
